require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'TestProject' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'Fattmerchant'

  target 'TestProjectTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'TestProject-tvOS' do
  # Pods for TestProject-tvOS

  target 'TestProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
